In [448]:
#Importamps Numpy con su abreviacion "np"
import numpy as np

In [449]:
#Podemos  crear arrays de una dimecion con la funcion np.array()
array_unidim = np.array([1, 2, 3,4,5])

In [450]:
#O un array de dos dimeciones (bidimencional)
array_bidim = np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [451]:
# O un array de tres dimenciones (tridimecional)
array_tridim = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [452]:
#Atributos del array unidimencional (forma, numero de dimenciones, tipo de datos, tamaño y tipo)
array_unidim.shape, array_unidim.ndim, array_unidim.dtype, array_unidim.size, type(array_unidim)

((5,), 1, dtype('int32'), 5, numpy.ndarray)

In [453]:
# Atributos del array bidimencional
array_bidim.shape, array_bidim.ndim, array_bidim.dtype, array_bidim.size, type(array_bidim)

((2, 5), 2, dtype('int32'), 10, numpy.ndarray)

In [454]:
# Atributos del array tridimecional
array_tridim.shape, array_tridim.ndim, array_tridim.dtype, array_tridim.size, type(array_tridim)

((4, 3), 2, dtype('int32'), 12, numpy.ndarray)

In [455]:
# Importamos pandas como pd, y creamos un DataFrame a partir del array bidimencional
import pandas as pd
datos = pd.DataFrame(array_bidim)
datos

,0,1,2,3,4
0,1,2,3,4,5
1,6,7,8,9,10


In [456]:
#Creamos un array de tamaño 4x3, formado unicamente por unos (1)
unos = np.ones((4,3))
unos

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [457]:
#Creamos un array de tamaño 2x4x3, formado unicamente por ceros (0)
ceros = np.zeros((2,4,3))
ceros

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [458]:
#Creamos un array de numeros en el rango de 0 a 100, con un paso de 5
array_1 = np.arange(0,100,5)
array_1

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [459]:
# Creamos un array de numeros aletorios enteros comprendidos entre 0 y 10, de tamaño (2,5)
array_2 = np.random.randint(0,10,(2,5))
array_2

array([[1, 2, 0, 3, 3],
       [5, 3, 5, 0, 7]])

In [460]:
#Creamos un array de numeros aletorios decimales comprendidos en entre 0 y 1, de tamaño (3,5)
array_3 = np.random.random((3,5))
array_3

array([[0.51357225, 0.22065617, 0.72557301, 0.84943495, 0.92889283],
       [0.73594004, 0.47658724, 0.49289297, 0.59452027, 0.07603697],
       [0.11747692, 0.96646567, 0.58332229, 0.09242191, 0.0136295 ]])

In [461]:
#Establecemos la "semilla" de numeros aletorios en 27
np.random.seed(27)
#Creamos un array de numeros aletorios enteros comprendidos en entre 0 y 10, de tamaño(3,5)
array_4 = np.random.randint(0,10,(3,5))
array_4

array([[3, 8, 8, 8, 0],
       [5, 8, 9, 1, 2],
       [1, 1, 4, 6, 3]])

In [462]:
#encontrar los valores unicos del array_4
np.unique(array_4)

array([0, 1, 2, 3, 4, 5, 6, 8, 9])

In [463]:
#Extramos el elemento del indice 1 del array_4
array_4[0]

array([3, 8, 8, 8, 0])

In [464]:
#Extramos las primeras dos filas del array_4
array_4[:2]

array([[3, 8, 8, 8, 0],
       [5, 8, 9, 1, 2]])

In [465]:
#Extramos los dos primeros datos de las primeras dos filas del array_4
array_4[:2,:2]

array([[3, 8],
       [5, 8]])

In [466]:
#Cramos dos arrays de tamaño 3x4 uno relleno de numeros aletorios entre 0 y 10 y otro relleno de unos
array_5 = np.random.randint(0,10,(3,4))
array_6 = np.ones((3,4))


In [467]:
#invocamos el array_5
array_5

array([[3, 0, 5, 3],
       [3, 6, 7, 2],
       [7, 8, 5, 7]])

In [468]:
#invocamos el array_6
array_6

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [469]:
#Sumamos los dos arrays
array_5+ array_6


array([[4., 1., 6., 4.],
       [4., 7., 8., 3.],
       [8., 9., 6., 8.]])

In [470]:
#Creamos ahora un array de tamaño (4,3) lleno de unos
array_7 = np.ones((4,3))
array_7

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [471]:
#Intentamos sumar los arrays 6 y 7
#array_6+ array_7
#No se puede ya que son diferentes dimenciones

In [472]:
#Entonces creamos otro array de tamaño (4,3) lleno de unos
array_8 = np.ones((4,3))

In [473]:
#Restamos el array_8 al array_7
array_8-array_7

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [474]:
#Creamos otros dos arrays de tanaño 3x3 con numeros aletorios del 1 al 5
array_9 = np.random.randint(1,5,(3,3))
array_10 = np.random.randint(1,5,(3,3))

In [475]:
#invocamos el array_9
array_9

array([[2, 3, 4],
       [1, 4, 4],
       [2, 3, 4]])

In [476]:
#Invocamos el array_10
array_10

array([[2, 1, 4],
       [4, 1, 2],
       [2, 4, 1]])

In [477]:
#Multiplicamos los ultimos dos arrays entre si
array_9*array_10

array([[ 4,  3, 16],
       [ 4,  4,  8],
       [ 4, 12,  4]])

In [478]:
#Elevamos el array_9 al cuadrado
array_9**2

array([[ 4,  9, 16],
       [ 1, 16, 16],
       [ 4,  9, 16]])

In [479]:
#Buscamos la raiz cuadrada del array_10
np.square(array_10)

array([[ 4,  1, 16],
       [16,  1,  4],
       [ 4, 16,  1]])

In [480]:
#Hallamos el promedio de los valores del array_9
array_9.mean()

3.0

In [481]:
#Hallamos el valor maximo de los valores del array_9
array_9.max()

4

In [482]:
#Hallamos el valor minimo de los valores del array_9
array_9.min()

1

In [483]:
#Cambiamos la forma del array_9 por una de 9x1, y lo almacenamos como array_11
array_11 = array_9.reshape((9,1))

In [484]:
#Invocamos el array_11
array_11

array([[2],
       [3],
       [4],
       [1],
       [4],
       [4],
       [2],
       [3],
       [4]])

In [485]:
#Transponemos el array_11
array_11.T

array([[2, 3, 4, 1, 4, 4, 2, 3, 4]])

In [486]:
#Comparamos el array_9 y el array_10 para saber cuales elementos del array_9 son mayores a los del array_10
array_12 = array_9 > array_10
array_12

array([[False,  True, False],
       [False,  True,  True],
       [False, False,  True]])

In [487]:
#Veamos sus nuevos tipos de datos
array_12.dtype

dtype('bool')

In [488]:
#Alguno de los elementos del array_9 es igual su equivalente del array_10?
array_9 == array_10

array([[ True, False,  True],
       [False, False, False],
       [ True, False, False]])

In [489]:
#Comparamos nuevamente ambos arrays, en esta ocacion con >=
array_9 >= array_10

array([[ True,  True,  True],
       [False,  True,  True],
       [ True, False,  True]])

In [492]:
#Buscamos los elementos del array_9 que son mayores a 2
array_9 >2

array([[False,  True,  True],
       [False,  True,  True],
       [False,  True,  True]])

In [494]:
#Ordenamos de menor a mayor los elementos dentro del array_9
np.sort(array_9)


array([[2, 3, 4],
       [1, 4, 4],
       [2, 3, 4]])